name: Deploy GitHub

on: [ push ]

jobs:
  build:
    container:
      image: 'emscripten/emsdk:3.1.20'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir -p Release/Web
          emcc -c -o Main.o @.vscode/Compile.rsp @.vscode/Compile.Release.rsp
          emcc Main.o -O2 @.vscode/Link.rsp @.vscode/Link.Release.rsp

      - name: Pack
        run: |
          cp Inflate.service.js Inflate.wasm Release/Web/
          cp favicon.ico Release/Web/
          cp -r example Release/Web/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Release/Web
          keep_files: true
